language: node_js
node_js:
  - "0.10"
matrix:
  include:
    - node_js: "0.10"
      env: UNDERSCORE=1.4.4 BACKBONE=1.0 MAINRUN=false
    - node_js: "0.10"
      env: UNDERSCORE=1.5 BACKBONE=1.0 MAINRUN=false
    - node_js: "0.10"
      env: UNDERSCORE=1.7 BACKBONE=1.1 MAINRUN=false
    - node_js: "0.10"
      env: UNDERSCORE=1.7 BACKBONE=1.0 MAINRUN=false
    - node_js: "0.10"
      env: UNDERSCORE=1.6 BACKBONE=1.0 MAINRUN=false
    - node_js: "0.10"
      env: UNDERSCORE=1.4.4 BACKBONE=1.1.0 MAINRUN=false
    - node_js: "0.10"
      env: UNDERSCORE=1.5 BACKBONE=1.1 MAINRUN=false
    - node_js: "0.10"
      env: LODASH=3.0 BACKBONE=1.1 MAINRUN=false
    - node_js: "0.10"
      env: LODASH=3.1 BACKBONE=1.0 MAINRUN=false
env: MAINRUN=true LODASH=false UNDERSCORE=latest
before_install:
  - npm config set ca ""
install:
  - npm install -g grunt-cli
  - npm install
  - npm dedupe
  - ./test/ci.sh
after_success:
  - if [[ $MAINRUN == true ]]; then npm run-script coverage; fi
